name: Build Termux Executable

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: Run
        run: |
           pip install uv
           wget -O cloud.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
           sudo  dpkg -i ./cloud.deb
           cloudflared tunnel --url http://localhost:8501 &
           sleep 15
           uv run python main.py
        
